### ISSUE TITLE
XP gain disables automatically after sometime

### ISSUE THREAD

**Issue by mikeross6233m** [FMCorz/moodle-block_xp#31] opened 2015-11-24 10:02 UTC
I am having some problem with a block_xp plugin.

Sometimes the block_xp shows "XP gain disable" and when I enable it after some time I notice the same thing.

**Comment by mikeross6233m** [comment] 2015-11-25 05:23
I noticed that whenever I restart my computer the xp gain disables.

**Comment by mikeross6233m** [comment] 2015-12-04 10:44
It is still happening every time..
Any suggestions??

**Comment by FMCorz** [comment] 2016-02-15 09:36
I can't reproduce this bug, did you find a solution or is it still happening?

**Comment by FMCorz** [comment] 2016-02-17 05:54
I'm closing this, please reopen a new issue if the problem remains.

**Closed by FMCorz** 2016-02-17 05:54 UTC
