### ISSUE TITLE
Getting XP from Comments

### ISSUE THREAD

**Issue by LennartBolduan** [FMCorz/moodle-block_xp#35] opened 2016-03-05 15:03 UTC
Dear Programmers,

In the new Moodle we found a new comment field in each class / course in Moodle. 

![image](https://cloud.githubusercontent.com/assets/6093995/13547864/3335668e-e2e2-11e5-98b0-02eb8714e76f.png)

Is is possible to get additional XP and activity protocoll of this element?

Kindly Lennart

**Comment by FMCorz** [comment] 2016-03-08 03:38
Hi,

Experience points should be earned for each comment posted as long as they are posted from a course. I tried using the block "Comments" and it worked.

Cheers,
Fred

**Comment by LennartBolduan** [comment] 2016-03-09 18:56
Bonjour Frédéric,

Okay thank YOU!

Hmmm, I will check it.... I checked it. I thaught I did MAYBE not start the
course - thats why it did not count XP but it was all correct.

Please find my problem attached.
https://drive.google.com/file/d/0B1MOvqwk61drczNWcG52bjdKMFU/view?usp=sharing


[image: Inline-Bild 1]

I tired to narrow it down. Maybe ther is just the entry in the rules
dropdown missing - seen on the screenshot. I added some explanations as
screencast.

Thank you so much for helping me out! In case this is a bigger programmer
and coding Job - please inform us so we can use our budget to solve the
problem. :)

Kindly Lennart Bolduan
Student at Berlin School of Economics and Law





----------------
Lennart Bolduan
Hochschule für Wirtschaft und Recht Berlin
mobile: 0176/20665154

2016-03-08 4:38 GMT+01:00 Frédéric Massart <notifications@github.com>:

**Comment by FMCorz** [comment] 2016-03-10 01:32
Hi Lennart,

Thanks a lot for the screencast. I have tried to replicate the configuration that appeared to be set but it worked out fine for me. Do you have access to the settings in the block? If yes, I would advise you to check the logs in which the event should appear, maybe it only contributes to 0 due to some rules.

Note that you may want to relax the cheat guard to make your testing easier.

What Moodle version are you using? What version of the block? Maybe a backup of the blocks in the course would help me finding the problem but everything seems to indicate that it resides outside of the block.

Cheers,
Fred

**Comment by LennartBolduan** [comment] 2016-03-10 07:04
Okay thanks for the advice. I will try it after my business trip some day
next week.

I will look for the log and deactivate the cheat guard. Good idea. :)

I am a little confused because i did not find the rule for that particular
comment block. There are a lot of comments for several objects like the
forum or wiki etc... but it seems that i can not select this block in the
"add rule" dropdown in the settings of the "Level Up / XP"-Settings.

I come back to you next week!

Thank you!
Kindly Lennart

----------------
Lennart Bolduan
Hochschule für Wirtschaft und Recht Berlin
mobile: 0176/20665154

2016-03-10 2:32 GMT+01:00 Frédéric Massart <notifications@github.com>:

**Comment by LennartBolduan** [comment] 2016-03-15 15:17
Dear Fred,

I have checked your ideas and recomendations. It did not help or work...
The Comment Block does not work with the XP Plug-in or Badges /
Achievements.

We also miss the option to give badges by rules. This is nicely shown in
this plugin for wordpress.

http://codecanyon.net/item/wpachievements-wordpress-achievements-plugin/4265703




Do you have any ideas how to handle this xp issue with the coment block?
Is it possible to ask for a cooperation in order to implove the existing
plugins?

Kindly Lennart


----------------
Lennart Bolduan
Hochschule für Wirtschaft und Recht Berlin
mobile: 0176/20665154

2016-03-10 8:03 GMT+01:00 Lennart Bolduan <lennart.bolduan@gmail.com>:

**Comment by FMCorz** [comment] 2016-03-16 01:02
Hi Lennart,

I am happy to cooperate in order to get your issue fixed, but first we need to identify the cause which is unclear at the moment.

Let's not mix-match too many things here. Badges are completely independent to block_xp, Achievements must also be something that is separate to the plugin itself.

Here are a few things I'd need answer on:

- What Moodle version are you using?
- What version of the plugin block_xp are you using?
- What version of the plugin block_comment are you using?
- Would you have an backup of the course that you could share with me? fred at fmcorz dot net

Thanks!
Fred

**Comment by FMCorz** [comment] 2016-03-27 04:34
Hi Lennart,

I have just sent you an email. I have used your backup and everything went fine, so I'm not quite sure what the problem could be.

Cheers,
Fred

**Comment by LennartBolduan** [comment] 2016-03-31 08:35
Okay. Would you mind checking my first E-Mail?

We can not find the XP option in the dropdown menue.

Kindly Lennart

----------------
Lennart Bolduan
Hochschule für Wirtschaft und Recht Berlin
mobile: 0176/20665154

2016-03-27 6:34 GMT+02:00 Frédéric Massart <notifications@github.com>:

**Comment by FMCorz** [comment] 2016-03-31 08:37
Erm... I'm confused.

What email?
What menu?
What "XP" option?

**Comment by FMCorz** [comment] 2016-04-01 08:32
Hi Lennart,

1/ Yes, it is possible. I have tested on my side, and using your backup and it did work.
2/ I'm afraid this is not possible at the moment, it is blocked by https://tracker.moodle.org/browse/MDL-39864
3/ That may be possible but it would require custom development, which is not directly related to block_xp

Cheers,
Fred

**Comment by FMCorz** [comment] 2016-04-07 05:46
Closing this as it does not appear to be a bug.

**Closed by FMCorz** 2016-04-07 05:46 UTC
Labels: question
