### ISSUE TITLE
error message after click on "Ladder"

### ISSUE THREAD

**Issue by gushagelberg2** [FMCorz/moodle-block_xp#94] opened 2019-03-04 09:53 UTC
When I click on "Ladder" in the plugin settings area, the following error appears (see attachment)
Exception - Argument 1 passed to block_xp\local\xp\user_state::__construct() must be an instance of stdClass, boolean given, called in [dirroot]/blocks/xp/classes/local/leaderboard/anonymised_leaderboard.php on line 83

![screen shot 2019-03-04 at 10 50 01](https://user-images.githubusercontent.com/22956703/53725097-909ad600-3e6b-11e9-92a1-593022a17e96.png)

Plugin Version: 2019020303
Moodle Version: Moodle 3.5.4+ (Build: 20190118)
Browser: Firefox 65.0.1

**Comment by FMCorz** [comment] 2019-03-05 02:12
Thanks for the report @gushagelberg2. It seems that your Moodle site is in a state where the _guest user_ does not exist. This should not happen as the guest user is created during site installation. Please double check whether you have overridden the config value `$CFG->siteguest` which should contain the ID of the guest user.

**Comment by gushagelberg2** [comment] 2019-03-12 14:04
Hi,
I have the guest user turned off on purpose. For data security reasons. Is the error then not avoidable if I don't allow guest users?

**Comment by FMCorz** [comment] 2019-03-13 03:38
@gushagelberg2 You don't have to allow _guest users_, but you must have the _guest user_ present in the database. Note that we raised this issue with Moodle too: https://tracker.moodle.org/browse/MDL-64991

**Comment by gushagelberg2** [comment] 2019-03-13 10:28
I added a user with the username "guest_user" but the error still appears. 
Could the problem have to do with groups? I noticed in another course that the error did not appear and I can not choose a group. In the course where the error appears, the error doesn't appear if I choose another group. 
![2019-03-13 11_22_28-Ladder](https://user-images.githubusercontent.com/22956703/54271794-7f944800-4582-11e9-816a-989c6c705a8a.png)

**Comment by FMCorz** [comment] 2019-06-03 04:09
The guest user is used when anonymising the leaderboard, so it's likely that another group's leaderboard didn't need to be anonymised. I will close this issue as it really seems to be caused by a missing guest user.

Please ask your administrator to confirm that the value of the admin config `siteguest` points to the right guest user. Usually the guest user is identified by ID `1`, but that may change depending on the system.

**Closed by FMCorz** 2019-06-03 04:09 UTC

**Comment by FMCorz** [comment] 2021-09-07 05:30
This issue appears related to a GDPR bug that would have been fixed in https://tracker.moodle.org/browse/MDL-69079 (https://github.com/moodle/moodle/commit/d6ec2d3e44700871fa9363d6805591af70e14811).

Upgrading to Moodle 3.9 should fix the issue.
